// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GeneratePageStream(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<string>;

export function SearchSuggestions(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;
