// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePage'](arg1, arg2, arg3);
}

export function GeneratePageStream(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GeneratePageStream'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchSuggestions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchSuggestions'](arg1, arg2, arg3);
}
